export const INCREMENT = 'INCREMENT ';
export const TASK_SET_LIST = 'TASK_SET_LIST';
export const TASK_ADD = 'ADD_TASK';
export const TASK_FILTER_SIDEBAR = 'TASK_FILTER_SIDEBAR';
export const SELECT_TASK = 'SELECT_TASK';
export const TASK_DELETE = 'TASK_DELETE';

export const CONNECTION_SET_LIST = 'CONNECTION_SET_LIST';
export const CONNECTION_GET_BY_ID = 'CONNECTION_GET_BY_ID';
export const CONNECTION_ADD = 'CONNECTION_ADD';
export const CONNECTION_REMOVE = 'CONNECTION_REMOVE';
